on:
  push:
    paths:
      - 'packages/chrome-extenstion-template/**'
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: 'ubuntu-18.04'
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: checkout
        run: |
          yarn
        working-directory: ./packages/chrome-extenstion-template
      - name: build
        run: |
          yarn build
        working-directory: ./packages/chrome-extenstion-template
