name: Node.js CI

on:
  push:
    paths:
      - 'packages/ts-lib-template/**'
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        working-directory: ./packages/ts-lib-template
        run: echo checkout
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn test
